// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlmxbnjftdifeyjanyrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sbXhibmpmdGRpZmV5amFueXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjYyMTEsImV4cCI6MjA2ODg0MjIxMX0.i3V96Vuc0xpkcR6aZomU4Iv68247MaZJ1rst5Ad7BGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});